version: "3"
services:
  servidorweb:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8044:80"
    command: chmod a+rxw /var/www/html
    command: chmod a+rxw /var/log/apache2
    volumes:
      - ./PHP:/var/www/html
      - ./logs:/var/log/apache2
    depends_on:
      - "bbdd"

  bbdd:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: bbdd
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PORT: 3306
    volumes:
      - ./.db_data:/var/lib/mysql
      - /Jenkins-Wordpress/scripts:/home/
      - ./.db_backup:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: "bbdd"
      PMA_USER: "root"
      PMA_PASSWORD: "secret"
    depends_on:
      - "bbdd"
    ports:
      - "8081:80"
